<a href="https://colab.research.google.com/github/leesihwan21/AI_26/blob/main/01_1_np%EC%99%80_%EC%B2%AB_%EB%A7%8C%EB%82%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [8]:
import numpy
print(numpy.array([1,2,3]))


[1 2 3]


In [9]:
import numpy as np

arr_1 = np.array([1,2,3,4,5]) # 파이썬 리스트를 넘파일 배열로 변환
print(arr_1) # 넘파일 배열 출력

[1 2 3 4 5]


In [11]:
[1,2,3,4,5] * 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
arr_1 * 2

array([ 2,  4,  6,  8, 10])

In [14]:
import numpy as np

arr_2 = np.array(
    [[1,2,3],
     [4,5,6,],
     [7,8,9]]

) # 파이썬 리스트를 ndarray로 변환
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
import numpy as np

arr_3 = np.array([[[1,2,3],
                   [4,5,6,]],
                  [[7,8,9],
                   [10,11,12]],
                  [[13,14,15],
                   [16,17,18]]]) # 파이썬 리스트를 넘파이 배열로 변환
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [17]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype)

int64


In [19]:
import numpy as np

print(np.array([1,2,3]).dtype)

int64


In [20]:
print(np.array([1,2,3], dtype='int8').dtype)

int8


In [21]:
print(np.array([1,2,3], dtype='i1').dtype)

int8


In [24]:
import numpy as np

ndarray_1 = np.array([1,2,3]) # 넘파이 배열
ndarray_2 = np.array([4,5,6]) # 넘파이 배열
list_1 = [1,2,3]
list_2 = [4,5,6]

In [25]:
print(ndarray_1 + ndarray_2)
print(list_1 + list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [26]:
result_list = [x + y for x, y in zip (list_1, list_2)]
print(result_list)

[5, 7, 9]


In [27]:
print(ndarray_1 * 2)
print(list_1 * 2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [30]:
import numpy as np

a = np.array([2,4,6]) # 넘파이 정수형 배열 생성
print(a)
print(a.dtype) # 넘파이 배열의 데이터 타입 출력
b = np.array([2.1, 3.2, 4.3]) # 넘파이 실수형 배열 생성
print(b)
print(b.dtype)

[2 4 6]
int64
[2.1 3.2 4.3]
float64


In [31]:
c = np.array(('i','j','k')) # 넘파이 문자열 배열 생성
print(c)
print(c.dtype) # 데이터 타입 확인


['i' 'j' 'k']
<U1


In [32]:
d = np.array((True, True, False)) # 넘파이 논리형 배열 생성
print(d)
print(d.dtype)


[ True  True False]
bool


In [33]:
e = np.array(['ab','cd','e'], dtype='<U2') # 문자열 길이를 조절하여 배열 생성
print(e)
print(e.dtype)

['ab' 'cd' 'e']
<U2


In [40]:
import numpy as np

# a 라는 변수에 (3,4) 크기의 넘파이 2차원 배열 생성
a = np.arange(12).reshape(3,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
import numpy as np

# 각 학급에 4명의 학생, 각 학생이 3과목의 시험 점수를 가지고 있는 배열 생성
# 예시 : 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어, 수학 점수
scores = np.random.randint(0,101,size=(3,4,3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열 (3차원 배열):")
print(scores)

# 학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
  print(f"\nClass {class_idx + 1}")
  for student_idx in range(scores.shape[1]):
    korean,english,math=scores[class_idx, student_idx]
    print(f"Student {student_idx + 1} - Korean: {korean}, English: {english}, Math: {math}")

학급별 학생들의 점수 배열 (3차원 배열):
[[[ 75  28  26]
  [ 67  21  36]
  [ 96  42   9]
  [  9  29  78]]

 [[ 19  78  31]
  [ 39   4  45]
  [ 56  58  60]
  [ 88   7  65]]

 [[100  85  54]
  [ 39  86  74]
  [ 57  84  55]
  [ 44  76  47]]]

Class 1
Student 1 - Korean: 75, English: 28, Math: 26
Student 2 - Korean: 67, English: 21, Math: 36
Student 3 - Korean: 96, English: 42, Math: 9
Student 4 - Korean: 9, English: 29, Math: 78

Class 2
Student 1 - Korean: 19, English: 78, Math: 31
Student 2 - Korean: 39, English: 4, Math: 45
Student 3 - Korean: 56, English: 58, Math: 60
Student 4 - Korean: 88, English: 7, Math: 65

Class 3
Student 1 - Korean: 100, English: 85, Math: 54
Student 2 - Korean: 39, English: 86, Math: 74
Student 3 - Korean: 57, English: 84, Math: 55
Student 4 - Korean: 44, English: 76, Math: 47


In [49]:
import numpy as np

# 1. (3,4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3,4)))
# 2. (3,4) 크기의 배열으르 데이터 타입을 정수로 생성한 후, 0으로 채움
print(np.zeros((3,4), dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [51]:
# (2,3,4)  크기의 배열을 생성하여 데이터 타입을 정수로 설정한 후 , 1로 채움
print(np.ones((2,3,4), dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [52]:
# (2,3) 크기의 빈 배열 생성
print(np.empty((2,3)))

[[1.77229299e-315 0.00000000e+000 5.60270442e-321]
 [1.85529919e-315 6.12641401e-322 1.85529855e-315]]


In [54]:
import numpy as np

# 10 이상 30 미만까지 5 간격으로 설절
print(np.arange(10,30,5))
# 0 이상 2 미만까지 0.3 간격으로 설정
print(np.arange(start=0, stop=2, step=0.3))


[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [55]:
# 1 ㅇ이상 10 이하까지 값을 가진 크기 10짜리 배열 생성
print(np.linspace(start=1, stop=10, num=10, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]


In [57]:
import numpy as np

# a와 b 배열 생성하여 출력
a = np.array([10,20,30,40])
b = np.arange(start=1, stop=5)
print(a)
print(b)

[10 20 30 40]
[1 2 3 4]


In [58]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [59]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2,0],
              [3,4]])

# 1. a * b : 요소별 곱셈 연산
print(a*b)
# 2. a @ b : 행렬 곱셈 사용
print(a@b)

[ 10  40  90 160]
300


In [62]:
import numpy as np

# A와 B 배열 생성
A = np.array([1,2,3,4])
B = np.array([1,1,3,3,])
# 비교 연산
print(A > B) # 1.
print(A == B) # 2.

[False  True False  True]
[ True False  True False]


In [66]:
import numpy as np

# 두 명의 학생의 시험 점수를 배열로 생성합니다.
student1_scores = np.array([85,90,78]) # 학생 1의 점수 (국어,영어,수학)
student2_scores = np.array([92,88,95]) # 학생 2의 점수 (국어,영어,수학)

# 두 학생의 점수를 출력합니다.
print("학생 1의 점수 : ", student1_scores)
print("학생 2의 점수 : ", student2_scores)

# 두 학생의 총점을 구합니다.
total_scores = student1_scores + student2_scores
print("두 학생의 총점 : ", total_scores)

# 두 학생의 평균 점수를 구합니다.
average_scores = total_scores / 2
print("두 학생의 평균 점수 : ", average_scores)

# 각 학생의 총점과 평균을 구합니다.
student1_total = np.sum(student1_scores)
student2_total = np.sum(student2_scores)
student1_average = np.mean(student1_scores)
student2_average = np.mean(student2_scores)

print("학생 1의 총점 : ", student1_total)
print("학생 1의 평균 점수 : ", student1_average)
print("학생 2의 총점 : ", student2_total)
print("학생 2의 평균 점수 : ", student2_average)

학생 1의 점수 :  [85 90 78]
학생 2의 점수 :  [92 88 95]
두 학생의 총점 :  [177 178 173]
두 학생의 평균 점수 :  [88.5 89.  86.5]
학생 1의 총점 :  253
학생 1의 평균 점수 :  84.33333333333333
학생 2의 총점 :  275
학생 2의 평균 점수 :  91.66666666666667


In [68]:
import numpy as np

# A 배열 생성
A = np.array([4,16,25])
# 1. 제곱근 함수
print(np.sqrt(A))


[2. 4. 5.]


In [70]:
# a 배열 생성 & 출력
# 0부터 8 미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2,4)**2
print(a)

[[ 0  1  4  9]
 [16 25 36 49]]


In [72]:
# 모든 요소의 합
print(a.sum())
# 모든 요소 중 평균
print(a.mean())
# 모든 요소 중 최댓값
print(a.max())
# 모든 요소의 누적합
print(a.cumsum())
# 모든 요소 중 최댓값의 인덱스
print(a.argmax())


140
17.5
49
[  0   1   5  14  30  55  91 140]
7


In [75]:
import numpy as  np

# 0부터 8미만 까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
# a = array([[0,1,4,9],
#           [16,25,3,49]])
a = np.arange(8).reshape(2,4)**2

# 1. axis = 0은 열 기준으로 연산
print(a.mean(axis = 0))
# 2. axis = 1은 행 기준으로 연산
print(a.max(axis=1))



[ 8. 13. 20. 29.]
[ 9 49]


In [77]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

# 인덱스가 0인, 인덱스가 3인 요소 출력
print(a[0])
print(a[3])

[0 1 2 3 4 5]
0
3


In [79]:
b = np.array([[0,1,2], [3,4,5]])
print(b)
print(b[1,0])
print(b[1,2])


[[0 1 2]
 [3 4 5]]
3
5


In [81]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

# 인덱스 0 이상 인덱스 3 미만 범위의 요소 출력
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [83]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

# a > 4 조건을 적용한 논리형 배열 생성
b = a > 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [84]:
print(a[b]) # 논리형 배열 b를 사용하여 조건에 맞는 요소를 추출
print(a[b].shape) # 추출한 요소들의 배열 모양


[ 5  6  7  8  9 10 11]
(7,)


In [85]:
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [87]:
import numpy as np

a = np.array(['a','b','c','d','e','f','g','h'])
i = np.array([1,1,3,4,])

# 배열 a에서 배열 i에 지정된 인덱스의 원소들을 출력
print(a[i]) # 2.
j = np.array([[3,4], [5,6]]) # 3.

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [88]:
b = np.array(['a','b','c','d'])
k = np.array([3,2,1,0])

# 배열 b에서 배열k에서 지정된 인덱스의 원소들을 재배열
b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [89]:
my_list = [10,20,30,40,50]
subset = my_list[1:4] # 인덱스 1 이상 4 미만 추출 (4는 포함되지 않음)
print(subset) # 20,30,40 출력

[20, 30, 40]


In [95]:
import numpy as np

my_array = np.array([10,20,30,40,50])
subset = my_array[1:4] # 인덱스 1 이상 4 미만 추출 (4는 포함되지 않음)
print(subset) # 출력 : [20,30,40]

[20 30 40]


In [98]:
import numpy as np


# 1. a 배열 생성
a = np.arange(12).reshape(3,4) # arange 는 0부터 11까지의 숫자로 이루어진 1차원 배열을 생성한후,
# reshape(3,4) 함수를 사용하여 배열을 3행 4열인 형태의 2차원 배열로 변환해줌.
print(a)
print(a.shape) # 3
print(a.ndim) # 4

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [105]:
# 1. reshape : 지정한 차원으로 변경하고 새로운 배열로 변환
b = a.reshape(2,6)
print(b)
print(b.shape)

# 2. 원본 a 배열은 기존의 (3,4) 형태 유지
print(a)
print(a.shape)




[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [104]:
# 1번째 매개변수에 -1을 전달해도 같은 결과가 나옴 (자동 계산)
c = a.reshape(-1,3)

In [108]:
import numpy as np

# 1. .resize() : 지정한 차원으로 변경하고 원본 배열 자체를 변경
a = np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)

# 2. 따로 반환하는 값 없음
print(a.resize(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [110]:
import numpy as np

a = np.arange(12).reshape(3,4)

# 1. ravel() : 1차원 배열로 크기 변경
print(a.ravel())
# 2. reshape(-1) : 1차원 배열로 크기 변경
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [112]:
import numpy as np

A = np.arange(12).reshape(2,6)
print(A)

# .T : [2,6]을 [6,2] 반환으로 전치(transpose) 변환
print(A.T)
print(A.T.shape)

# 만약에 전치 형태로 원본 A 배열에 저장하고 싶다면, A 배열에 A.T 값을 할당
A = A.T
print(A)
print(A.shape)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [113]:
import numpy as np

# a 배열, b 배열 생성
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

# 1. 수직으로 합치기
print(np.vstack((a,b)))
# 2. 수평으로 합치기
print(np.hstack((a,b)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [114]:
import numpy as np

# a 배열, b 배열 생성
a = np.arange(12).reshape(2,6)
print(a)

# 1 수직으로 분할하기
print(np.vsplit(a,2))
# 2 수평으로 분할하기
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
